<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LuckyGuard.Windows</RootNamespace>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LuckyGuard.Core\LuckyGuard.Core.csproj" />
    <ProjectReference Include="..\LuckyGuard.Ioc\LuckyGuard.Ioc.csproj" />
  </ItemGroup>
</Project>
